"""Kevin - a creativity-routing architecture.

Creativity is not generated by relaxing constraints, but by *routing* between
unexplored solution spaces, wild variation, method transfer, and epistemic
selection - and then letting a human choose meaning and direction.

Public surface:

    from kevin import Kevin, Problem
    from kevin.human_gate import build_briefing

    kevin = Kevin()
    run = kevin.run(Problem("how do we make onboarding feel less like paperwork?"))
    print(build_briefing(run).render())
"""

from __future__ import annotations

from .method_library import MethodLibrary, extract_method
from .models import (
    Affinity,
    Candidate,
    CreativeRun,
    Evaluation,
    Method,
    Problem,
    SolutionSpace,
    Variant,
    Verdict,
    WildMove,
)
from .orchestrator import Kevin

__all__ = [
    "Kevin",
    "Problem",
    "SolutionSpace",
    "Variant",
    "Method",
    "Candidate",
    "Evaluation",
    "CreativeRun",
    "MethodLibrary",
    "extract_method",
    "Affinity",
    "Verdict",
    "WildMove",
]

__version__ = "0.1.0"
