"""Kevin - the orchestrator (the Dirigent).

This is the whole architecture in one routing pass. It owns no creativity of its
own; it *routes* between the engines in the order the design prescribes, and records
everything into a replay-stable ``CreativeRun``.

    1. explore       - find plausible, under-worked solution spaces        (DESi-flavoured)
    2. route         - select only the under-explored ones                 (logic)
    3. vary          - send the wild brother in                            (LLM language)
    4. transfer      - discipline the wildest variants with Layer-9 methods (shape transfer)
    5. select        - keep what is coherent / testable / connected         (DESi selection)
    6. brief         - hand a ranked possibility space to the human         (no decision)

The thesis, in code:

    Creativity is not generated by relaxing constraints, but by routing between
    unexplored solution spaces, wild variation, method transfer, and epistemic
    selection. The human chooses meaning and direction.
"""

from __future__ import annotations

from .llm_client import LLMClient, get_default_client
from .method_library import MethodLibrary
from .models import Candidate, CreativeRun, Problem, Variant
from .selector import Selector
from .solution_space import SolutionSpaceExplorer
from .wild_brother import WildBrother


class Kevin:
    def __init__(
        self,
        llm: LLMClient | None = None,
        *,
        library: MethodLibrary | None = None,
    ) -> None:
        self._llm = llm or get_default_client()
        self._explorer = SolutionSpaceExplorer(self._llm)
        self._wild = WildBrother(self._llm)
        self._library = library or MethodLibrary()
        self._selector = Selector(self._llm)

    @property
    def library(self) -> MethodLibrary:
        return self._library

    def run(
        self,
        problem: Problem,
        *,
        top_spaces: int = 2,
        methods_per_target: int = 1,
        discipline_threshold: float = 0.7,
    ) -> CreativeRun:
        """One full creative pass. Deterministic given the same LLM.

        ``discipline_threshold`` decides which variants are wild enough to *need* a
        transferred method: the tamer ones go forward as raw candidates, the wildest
        ones are disciplined by Layer 9 - the strongest case in the design.
        """
        run = CreativeRun(problem=problem)

        # 1-2. explore and route to under-worked, plausible regions.
        run.spaces = self._explorer.explore(problem)
        chosen = self._explorer.select_underexplored(problem, top_k=top_spaces)
        run.chosen_spaces = [s.id for s in chosen]

        # 3. wild variation, only inside the routed spaces.
        run.variants = self._wild.storm(problem, chosen)

        # 4-5. build candidates: raw for tame variants, method-disciplined for wild ones.
        space_by_id = {s.id: s for s in run.spaces}
        for variant in run.variants:
            if variant.wildness >= discipline_threshold:
                run.candidates.extend(
                    self._discipline(run, variant, space_by_id, methods_per_target)
                )
            else:
                run.candidates.append(self._raw_candidate(variant))

        run.evaluations = self._selector.select(problem, run.candidates)
        return run

    # -- helpers ------------------------------------------------------------ #
    def _raw_candidate(self, variant: Variant) -> Candidate:
        return Candidate(
            content=variant.content,
            space_id=variant.space_id,
            variant_id=variant.id,
            wildness=variant.wildness,
        )

    def _discipline(
        self, run: CreativeRun, variant: Variant, space_by_id: dict, methods_per_target: int
    ) -> list[Candidate]:
        """Transfer matching Layer-9 methods onto a wild variant -> disciplined candidates."""
        space = space_by_id.get(variant.space_id)
        affinities = space.affinities if space else ()
        methods = self._library.match(affinities, top_k=methods_per_target)
        if not methods:
            return [self._raw_candidate(variant)]

        candidates: list[Candidate] = []
        for method in methods:
            transfer = self._library.transfer(self._llm, method, variant.id, variant.content)
            run.transfers.append(transfer)
            disciplined_text = (
                f"{variant.content}  |  via '{method.name}': "
                + "; ".join(transfer.mapped_steps)
            )
            candidates.append(
                Candidate(
                    content=disciplined_text,
                    space_id=variant.space_id,
                    variant_id=variant.id,
                    transfer_id=transfer.id,
                    wildness=variant.wildness,
                )
            )
        return candidates
